name: Awesome Inc Jobs Board
permalink: pretty

collections:
  employers:
    permalink: /employers/:path/
    output: true
  candidates:
    permalink: /candidates/:path/
    output: true
  jobs:
    permalink: /jobs/:path/
    output: true